fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    postgresql: git://github.com/puppetlabs/puppetlabs-postgresql.git
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      branch: 2.2.x
  symlinks:
    barman: "#{source_dir}"
