fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    postgresql: git://github.com/puppetlabs/puppetlabs-postgresql.git
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
  symlinks:
    barman: "#{source_dir}"
