name 'it2ndq-barman'
version '0.2.0'
source 'git://github.com/2ndquadrant-it/puppet-barman.git'
author 'it2ndq'
license 'GPL v3'
summary 'Barman (Backup and Recovery Manager for PostgreSQL) module'
description 'Automates Barman installation and server setup'
project_page 'http://github.com/2ndquadrant-it/puppet-barman'

dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
