name 'deviseit-barman'
version '0.2.0'
source 'git://github.com/deviseit/puppet-barman.git'
author 'deviseit'
license 'GPL v3'
summary 'BaRMan module'
description 'Automates barman installation and server setup'
project_page 'http://github.com/deviseit/puppet-barman'

dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
